### ISSUE TITLE
ROS buildfarm Mdev build failure

### ISSUE THREAD

**Issue by at-wat** [openspur/yp-spur#100]
http://build.ros.org/view/Mdev/job/Mdev__yp-spur__ubuntu_bionic_amd64/17/console
http://build.ros.org/view/Mdev/job/Mdev__yp-spur__ubuntu_bionic_amd64/18/console

Looks caused by the build farm config for build_tool_depend cmake.
Another cmake package is also failing. http://build.ros.org/view/Mdev/job/Mdev__rc_genicam_api__ubuntu_bionic_amd64/17/console

**Comment by at-wat** [comment]
## Mdev__yp-spur__ubuntu_bionic_amd64
```
14.3. run tests

# BEGIN SUBSECTION: run tests
21:28:31 Invoking '. /opt/ros/melodic/setup.sh && . /tmp/ws/devel_isolated/setup.sh && PYTHONIOENCODING=utf_8 PYTHONUNBUFFERED=1 catkin_make_isolated --force-cmake --cmake-args -DBUILD_TESTING=1 -DCATKIN_ENABLE_TESTING=1 -DCATKIN_SKIP_TESTING=0 -DCATKIN_TEST_RESULTS_DIR=/tmp/ws/test_results --catkin-make-args run_tests' in '/tmp/ws'
21:28:31 /bin/sh: 4: .: Can't open /tmp/ws/devel_isolated/ypspur/setup.sh
21:28:31 # END SUBSECTION
```

using `devel_isolated/ypspur/setup.sh`???

## Kdev__yp-spur__ubuntu_xenial_amd64
```
14.3. run tests

# BEGIN SUBSECTION: run tests
02:02:25 Invoking '. /opt/ros/kinetic/setup.sh && . /tmp/ws/devel_isolated/setup.sh && PYTHONIOENCODING=utf_8 PYTHONUNBUFFERED=1 catkin_make_isolated --force-cmake --cmake-args -DBUILD_TESTING=1 -DCATKIN_ENABLE_TESTING=1 -DCATKIN_SKIP_TESTING=0 -DCATKIN_TEST_RESULTS_DIR=/tmp/ws/test_results --catkin-make-args run_tests' in '/tmp/ws'
02:02:25 Base path: /tmp/ws
```

**Comment by at-wat** [comment]
https://github.com/ros/catkin/pull/1000
My PR has been merged and all downstream packages are rebuilding.

**Comment by dirk-thomas** [comment]
With the new `catkin` version in the testing repo the latest devel build passed again.

**Comment by at-wat** [comment]
thanks @dirk-thomas !
