### ISSUE TITLE
Error occured when compiling ypspur_ros with release version

### ISSUE THREAD

**Issue by aislab** [openspur/yp-spur#42]
I installed the software according to https://github.com/openspur/yp-spur/wiki so that I would like to use[ ypspur_ros](https://github.com/openspur/ypspur_ros) in the indigo environment.
But it seems that ypspur-config.cmake will not be installed on release version.

I compiled ypspur-ros instaled yp-spur (commit ver. de084f3).
```
$catkin build ypspur_ros
Errors     << ypspur_ros:cmake /home/USER/hoge-project/catkin_ws/logs/ypspur_ros/build.cmake.005.log
CMake Error at /home/USER/hoge-project/catkin_ws/src/ypspur_ros/CMakeLists.txt:41 (find_package):
  By not providing "Findypspur.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ypspur", but
  CMake did not find one.

  Could not find a package configuration file provided by "ypspur" with any
  of the following names:

    ypspurConfig.cmake
    ypspur-config.cmake

  Add the installation prefix of "ypspur" to CMAKE_PREFIX_PATH or set
  "ypspur_DIR" to a directory containing one of the above files.  If "ypspur"
  provides a separate development package or SDK, be sure it has been
  installed.
```

I tried build the latest yp-spur.
It requires cmake3, but we use cmake as 2.8.6 in our environment.
Could you change CMakeLists.txt of yp-spur so that it can be executed with cmake2 ?

thanks.

**Comment by at-wat** [comment]
The latest yp-spur package uses cmake 3 functions for package versioning.

Does `cmake2.8` branch work?

**Comment by aislab** [comment]
The following error occurred in cmake2.8 branch.

```
$ cmake ../

CMake Error at auxlib/CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.0.2 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
```

**Comment by at-wat** [comment]
It seems requiring several workarounds to downgrade cmake version.
I'll look into it.

**Comment by at-wat** [comment]
@aislab The current master branch should work with CMake 2.8 on Ubuntu 14.04. Please try it out.

**Comment by disktnk11** [comment]
It compiled successfully.
Thanks.

**Comment by aislab** [comment]
It compiled successfully.
Thanks.
